# Generated by Django 3.0.3 on 2020-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0002_auto_20200507_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(blank=True, null=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=30)),
                ('flow_duration', models.BigIntegerField(blank=True, null=True)),
                ('flow_pps', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
