# Generated by Django 3.0.6 on 2020-05-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0005_djangoboard_ddos_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoboard',
            old_name='ddos_label',
            new_name='ddoslabel',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='dst_ip',
            new_name='dstip',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='dst_port',
            new_name='dstport',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='flow_duration',
            new_name='flowduration',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='flow_pps',
            new_name='flowpps',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='src_ip',
            new_name='srcip',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='src_port',
            new_name='srcport',
        ),
    ]
