# Generated by Django 3.0.6 on 2020-05-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0006_auto_20200527_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoboard',
            old_name='flowpps',
            new_name='flowpackets_s',
        ),
        migrations.RenameField(
            model_name='djangoboard',
            old_name='ddoslabel',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='num',
        ),
    ]
